name: CompatHelper

on:
  schedule:
    - cron: '00 04 * * 4'
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install CompatHelper
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.add("CompatHelper")
          CompatHelper.main(; subdirs)
